name: single_cell
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-build
  - R
  - rust=1.63.0
  - gseapy==0.13.0
  - igraph=0.9.10
  - jax=0.3.16
  - jaxlib=0.3.15
  - leidenalg=0.8.10
  - matplotlib=3.5.3
  - networkx=2.8.6
  - numba=0.55.2
  - numpy=1.22.4
  - scrublet=0.2.3
  - python=3.10.6
  - scanpy=1.9.1
  - scikit-learn=1.1.2
  - scipy=1.9.0
  - seaborn=0.12.0
  - statsmodels=0.13.2
  - umap-learn=0.5.3
  - cmake
  - git
  - lightgbm
  - pip
  - python-annoy
  - pip:
    - streamlit 
    - git+https://github.com/YosefLab/Hotspot.git@c8bc56d689cc0b770ca59080e194a2d9e93f3c5e
    - bbknn==1.5.1
    - cython==0.29.32
    - harmony-pytorch==0.1.7
    - hnswlib==0.6.2
    - louvain==0.7.1
    - markdown==3.4.1
    - pandas==1.4.4
    - pegasusio==0.7.1
    - pegasuspy==1.7.1
    - pot==0.8.2
    - pyro-api==0.1.2
    - pyro-ppl==1.8.1
    - pyrsistent==0.18.1
    - python-igraph==0.9.11
    - pytorch-lightning==1.6.5
    - scanorama==1.7.2
    - scib==1.0.3
    - scikit-misc==0.1.4
    - scvi-tools==0.17.1
    - statannotations==0.4.4
    - torch==1.12.1
    - torchmetrics==0.9.3
    - wot==1.0.8.post2
    - scarches
    - plotly