channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cxx-compiler
  - conda-build
  - leidenalg=0.8.10
  - matplotlib=3.5.3
  - networkx=2.8.6
  - numba=0.55.2
  - numpy=1.22.4
  - python=3.10.6
  - scanpy=1.9.1
  - scikit-learn=1.1.2
  - scipy=1.9.0
  - seaborn=0.12.0
  - statsmodels=0.13.2
  - umap-learn=0.5.3
  - cmake
  - lightgbm
  - pip
  - python-annoy
  - ipykernel
  - scikit-misc
  - pip:
    - pandas==1.4.4
    - pegasusio==0.7.1
    - pegasuspy==1.7.1
    - python-igraph==0.9.11
    - statannotations==0.4.4
    - fbpca
    - mquad
    - textalloc