channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cxx-compiler
  - fortran-compiler
  - cython
  - conda-build
  - leidenalg
  - matplotlib
  - networkx
  - numba
  - numpy
  - python=3.9
  - scanpy
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - umap-learn
  - cmake
  - lightgbm
  - pip
  - python-annoy
  - ipykernel
  - pip:
    - pandas
    - pegasusio
    - pegasuspy
    - python-igraph
    - statannotations
    - mquad
    - textalloc
